### ISSUE TITLE
Make repo independent + new name?

### ISSUE THREAD

**Issue by balerion** [momentoscope/hextof-processor#18]
Currently this repo is a fork of Yves' repo. I suspect this means the idea would be to eventually merge the two with a pull request. Somehow, I think we should consider keeping the two completely separated, so that we might have Yves' repo as a legacy reference.

I am not sure I understand the consequences entirely, so if I am just asking for trouble, please let me know.

In any case, if we decide to act in this direction, it is possible to contact github to let them know we want to make this repo independent, and it should be a straightforward process.

**Comment by RealPolitiX** [comment]
It's a necessary move at some point. This won't affect Yves' original repo since you don't have the master-level rights to delete it

**Comment by RealPolitiX** [comment]
I propose to change the name to hextof instead, easier to write

**Comment by balerion** [comment]
I can also remove XPSdoniachs and put it on my repo, maybe just leave a link in the readme if it makes things easier

**Comment by steinnymir** [comment]
I agree with making this independent of Yves original repo, and also changing its name.

I will wait for Yves to confirm if he is ok with this, (Davide wrote him) and if we hear nothing till the end of the week I will proceed with the separation anyway next Monday.

Concerning name, I think **hextof-processor** is the most appropriate name, and the easiest to read and to write (no camel case, - instead of _. This appears to be the most common standard on github) but I am also ok with other options.

Also this can be done already, so I would proceed as soon as I get some positive feedback.

**Comment by RealPolitiX** [comment]
**hextof-processor** sounds fine with me. When I built the documentation, I only referenced the files in the processor folder, so there will be no conflict in the separation.

**Comment by RealPolitiX** [comment]
@balerion if you are actively using the XPSdoniachs folder, why not just keep it there. It's good to have an example of how that is used.

**Comment by balerion** [comment]
So everyone involved has approved shifting to normal mode. @steinnymir would you take care of this please?

**Comment by steinnymir** [comment]
I will do this next monday.

**Comment by balerion** [comment]
awesome! thanks

**Comment by steinnymir** [comment]
repo is now independent and name has changed to **hextof-processor** as discussed.
