### ISSUE TITLE
Clean up comments, readme and generate documentation

### ISSUE THREAD

**Issue by balerion** [momentoscope/hextof-processor#3]
We need to do some serious cleanup regarding the readme and creating the documentation. Examples need to be moved to comments in the code, and the documentation page needs to be generated.

**Comment by RealPolitiX** [comment]
The first version of the documentation is built as html (you can pull the current version and view the **index.html** in browser), just looking for a good host such that it can be accessed online.

**Comment by balerion** [comment]
what about https://pages.github.com
?

**Comment by RealPolitiX** [comment]
I used sphinx for doc generation, which gave no problems, but the readthedocs website can't rebuild it well, http://hextofofflineanalyzer.readthedocs.io/en/latest/
It's missing texts present in the docs folder which I think is because this is not yet an official installable package
Github pages use jekyll to render, but it seems that it's no trivial task to get it working with github pages and jekyll, https://jefflirion.github.io/sphinx-github-pages.html
the current status is like this...
https://momentoscope.github.io/HextofOfflineAnalyzer/

**Comment by RealPolitiX** [comment]
I'll try to implement the approach from https://jefflirion.github.io/sphinx-github-pages.html

**Comment by RealPolitiX** [comment]
Great, it's working now!

**Comment by RealPolitiX** [comment]
@balerion @steinnymir The latest version of documentation is uploaded. I have incorporated most of the readme into the formal documentation. In principle we can delete point 1-4 in the README.md
@balerion Is point 5 in the README.md the same as in the utils docstring?

**Comment by RealPolitiX** [comment]
Close this as recent changes have been mirrored in the documentation.
